# Generated by Django 3.0.5 on 2020-04-13 07:56

import django.core.validators
from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('count', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('lastname', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(150)])),
                ('contactno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('city', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveySecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.PositiveIntegerField(default=0)),
                ('diabetes', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('highbp', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('heart', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('lung', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('stroke', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('immunity', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.PositiveIntegerField(default=0)),
                ('sorethroat', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('chestpain', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('cough', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('breathing', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('weak', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('foreigntrip', models.CharField(blank='false', choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('feverhave', models.ForeignKey(blank='false', on_delete=django.db.models.fields.related.ForeignKey, to='survey.Fever')),
            ],
        ),
    ]
